apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  default.conf: |
    server {
        listen 80;

        # Serve React static files
        root /usr/share/nginx/html;
        index index.html;

        # Handle React routing (SPA)
        location / {
            try_files $uri /index.html; # If the file doesn't exist, fallback to index.html
        }

        # Forward API requests to the backend
        location /api/ {
            proxy_pass {{ .Values.env.API_PROXY_URL }}; # Use Helm value
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Handle 404 errors by serving index.html
        error_page 404 /index.html;
    }
