apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: dev-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_DB
              value: lilashop_db
            - name: POSTGRES_USER
              value: lilashop_user
            - name: POSTGRES_PASSWORD
              value: lilashop_password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-script-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script-volume
          configMap:
            name: {{ .Release.Name }}-init-scripts
